name: LeetCode Email Monitor

on:
  schedule:
    - cron: '30 19-23,0-7 * * *'  # Runs at the 30th minute of hours 19-23 and 0-7 UTC

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Or specify your preferred version (e.g., '3.9')

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run LeetCode monitoring script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python email_monitor.py